version: '3.8'

services:
  servicioejeucion:
    build: .
    container_name: arryn-servicioejeucion
    restart: unless-stopped
    environment:
      - MONGODB_CONNECTION_STRING=${MONGODB_CONNECTION_STRING}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME:-smartcompare_ai}
      - COLLECTION_NAME=${COLLECTION_NAME:-products}
    volumes:
      - ./logs:/app/logs
      - ./scraped_output:/app/scraped_output  
      - ./backups:/app/backups
    ports:
      - "8080:8080"
    networks:
      - arryn-network
    healthcheck:
      test: ["CMD", "python", "-c", "print('healthy')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  arryn-network:
    driver: bridge